### ISSUE TITLE
Issue downloading dependencies

### ISSUE THREAD

**Issue by BenjaminRocco** [felipefialho/piano#243]
Hello, I'm having an issue getting started: 

```
(base) ben@Benjamins-MBP piano-keyboard % npm -v
10.4.0
(base) ben@Benjamins-MBP piano-keyboard % npm install
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /Users/ben/.npm/_cacache/tmp/674b177c
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/Users/ben/.npm"

npm ERR! Log files were not written due to an error writing to the directory: /Users/ben/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
(base) ben@Benjamins-MBP piano-keyboard % sudo chown -R 501:20 "/Users/ben/.npm" 
(base) ben@Benjamins-MBP piano-keyboard % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: piano@2.1.0
npm ERR! Found: webpack@3.12.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^3.12.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0 || ^5.0.0" from file-loader@6.2.0
npm ERR! node_modules/file-loader
npm ERR!   dev file-loader@"6.2.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/ben/.npm/_logs/2024-01-29T18_21_25_212Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/ben/.npm/_logs/2024-01-29T18_21_25_212Z-debug-0.log
(base) ben@Benjamins-MBP piano-keyboard % npm install --force
npm WARN using --force Recommended protections disabled.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: file-loader@6.2.0
npm WARN Found: webpack@3.12.0
npm WARN node_modules/webpack
npm WARN   dev webpack@"^3.12.0" from the root project
npm WARN   3 more (babel-loader, clean-webpack-plugin, html-webpack-plugin)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer webpack@"^4.0.0 || ^5.0.0" from file-loader@6.2.0
npm WARN node_modules/file-loader
npm WARN   dev file-loader@"6.2.0" from the root project
npm WARN 
npm WARN Conflicting peer dependency: webpack@5.90.0
npm WARN node_modules/webpack
npm WARN   peer webpack@"^4.0.0 || ^5.0.0" from file-loader@6.2.0
npm WARN   node_modules/file-loader
npm WARN     dev file-loader@"6.2.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: pug-loader@2.4.0
npm WARN Found: pug@3.0.2
npm WARN node_modules/pug
npm WARN   dev pug@"^3.0.2" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer pug@"^2.0.0" from pug-loader@2.4.0
npm WARN node_modules/pug-loader
npm WARN   dev pug-loader@"^2.3.0" from the root project
npm WARN 
npm WARN Conflicting peer dependency: pug@2.0.4
npm WARN node_modules/pug
npm WARN   peer pug@"^2.0.0" from pug-loader@2.4.0
npm WARN   node_modules/pug-loader
npm WARN     dev pug-loader@"^2.3.0" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: webpack-dev-server@4.15.1
npm WARN Found: webpack@3.12.0
npm WARN node_modules/webpack
npm WARN   dev webpack@"^3.12.0" from the root project
npm WARN   3 more (babel-loader, clean-webpack-plugin, html-webpack-plugin)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional webpack@"^4.37.0 || ^5.0.0" from webpack-dev-server@4.15.1
npm WARN node_modules/webpack-dev-server
npm WARN   dev webpack-dev-server@"^4.15.1" from the root project
npm WARN 
npm WARN Conflicting peer dependency: webpack@5.90.0
npm WARN node_modules/webpack
npm WARN   peerOptional webpack@"^4.37.0 || ^5.0.0" from webpack-dev-server@4.15.1
npm WARN   node_modules/webpack-dev-server
npm WARN     dev webpack-dev-server@"^4.15.1" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated acorn-dynamic-import@2.0.2: This is probably built in to whatever tool you're using. If you still need it... idk
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated @types/svgo@3.0.0: This is a stub types definition. svgo provides its own type definitions, so you do not need this installed.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated svgo@0.7.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 1776 packages, and audited 1777 packages in 2m

144 packages are looking for funding
  run `npm fund` for details

133 vulnerabilities (92 moderate, 37 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
(base) ben@Benjamins-MBP piano-keyboard % npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating css-loader to 6.9.1, which is a SemVer major change.
npm WARN audit Updating lost to 9.0.2, which is a SemVer major change.
npm WARN audit Updating rucksack-css to 0.1.2, which is a SemVer major change.
npm WARN audit Updating autoprefixer to 10.4.17, which is a SemVer major change.
npm WARN audit Updating cssnano to 6.0.3, which is a SemVer major change.
npm WARN audit Updating postcss-loader to 8.0.0, which is a SemVer major change.
npm WARN audit Updating offline-plugin to 0.0.1, which is a SemVer major change.
npm WARN audit Updating babel-core to 4.7.16, which is a SemVer major change.
npm WARN audit Updating webpack to 5.90.0, which is a SemVer major change.
npm WARN audit Updating html-webpack-plugin to 5.6.0, which is a SemVer major change.
npm WARN audit Updating copy-webpack-plugin to 12.0.2, which is a SemVer major change.
npm WARN audit No fix available for postcss-font-magician@*
npm WARN audit Updating babel-loader to 9.1.3, which is a SemVer major change.
npm WARN audit Updating stylint to 0.6.3, which is a SemVer major change.
npm WARN audit Updating imagemin-webpack-plugin to 2.1.5, which is a SemVer major change.
npm WARN audit Updating webpack-pwa-manifest to 4.0.0, which is a SemVer major change.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: pug-loader@2.4.0
npm WARN Found: pug@3.0.2
npm WARN node_modules/pug
npm WARN   dev pug@"^3.0.2" from the root project
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer pug@"^2.0.0" from pug-loader@2.4.0
npm WARN node_modules/pug-loader
npm WARN   dev pug-loader@"^2.3.0" from the root project
npm WARN 
npm WARN Conflicting peer dependency: pug@2.0.4
npm WARN node_modules/pug
npm WARN   peer pug@"^2.0.0" from pug-loader@2.4.0
npm WARN   node_modules/pug-loader
npm WARN     dev pug-loader@"^2.3.0" from the root project
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated left-pad@0.0.3: use String.prototype.padStart()
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated browserslist@0.4.0: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated line-numbers@0.2.0: Copy its ~20 LOC directly into your code instead.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated chokidar@0.12.6: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated rucksack-css@0.1.2: Rucksack has moved to PostCSS! This version is no longer maintained. Update and use PostStylus (https://github.com/seaneking/poststylus) to continue using Rucksack as a Stylus plugin
npm WARN deprecated fsevents@0.3.8: "Please update to latest v2.3 or v2.2"
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated core-js@0.6.1: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/ben/piano-keyboard/node_modules/optipng-bin
npm ERR! command failed
npm ERR! command sh -c node lib/install.js
npm ERR! fs.js:43
npm ERR! } = primordials;
npm ERR!     ^
npm ERR! 
npm ERR! ReferenceError: primordials is not defined
npm ERR!     at fs.js:43:5
npm ERR!     at req_ (/Users/ben/piano-keyboard/node_modules/natives/index.js:143:24)
npm ERR!     at Object.req [as require] (/Users/ben/piano-keyboard/node_modules/natives/index.js:55:10)
npm ERR!     at Object.<anonymous> (/Users/ben/piano-keyboard/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1235:19)
npm ERR!     at require (node:internal/modules/helpers:176:18)
npm ERR! 
npm ERR! Node.js v20.11.0

npm ERR! A complete log of this run can be found in: /Users/ben/.npm/_logs/2024-01-29T18_24_26_830Z-debug-0.log

```

So now I am currently trying to use npm to download these dependencies but I cannot get past this step. Any help is greatly appreciated, thank you.

**Comment by Railson95** [comment]
Eu também estou com o mesmo problema!

**Comment by felipefialho** [comment]
@BenjaminRocco @Railson95 Sorry for the delay, I hadn't seen this issue earlier 😶

This is an older project, so some dependencies are deprecated in newer Node versions. I’ve made some changes to the Webpack configuration to ensure compatibility with the latest Node versions

Could you test it again and let me know if everything works as expected? 🙏 

Thanks!

**Comment by thiagopbraga** [comment]
Hello everyone, this problem persists, does anyone know how to fix this?

**Comment by felipefialho** [comment]
@thiagopbraga Is it exactly the same error? I can't replicate this anymore
